/**
 * BIA Design System — Design Token Types
 * Generated from tokens.css
 * 
 * This file contains TypeScript types and constants for all design tokens
 * defined in packages/core/src/styles/tokens.css
 */

export type PrimitiveColorToken =
  | 'base-black'
  | 'base-transparent'
  | 'base-white'
  | 'blue-100'
  | 'blue-200'
  | 'blue-25'
  | 'blue-300'
  | 'blue-400'
  | 'blue-50'
  | 'blue-500'
  | 'blue-600'
  | 'blue-700'
  | 'blue-800'
  | 'blue-900'
  | 'blue-950'
  | 'blue-dark-100'
  | 'blue-dark-200'
  | 'blue-dark-25'
  | 'blue-dark-300'
  | 'blue-dark-400'
  | 'blue-dark-50'
  | 'blue-dark-500'
  | 'blue-dark-600'
  | 'blue-dark-700'
  | 'blue-dark-800'
  | 'blue-dark-900'
  | 'blue-dark-950'
  | 'blue-light-100'
  | 'blue-light-200'
  | 'blue-light-25'
  | 'blue-light-300'
  | 'blue-light-400'
  | 'blue-light-50'
  | 'blue-light-500'
  | 'blue-light-600'
  | 'blue-light-700'
  | 'blue-light-800'
  | 'blue-light-900'
  | 'blue-light-950'
  | 'brand-100'
  | 'brand-200'
  | 'brand-25'
  | 'brand-300'
  | 'brand-400'
  | 'brand-50'
  | 'brand-500'
  | 'brand-600'
  | 'brand-700'
  | 'brand-800'
  | 'brand-900'
  | 'brand-950'
  | 'cyan-100'
  | 'cyan-200'
  | 'cyan-25'
  | 'cyan-300'
  | 'cyan-400'
  | 'cyan-50'
  | 'cyan-500'
  | 'cyan-600'
  | 'cyan-700'
  | 'cyan-800'
  | 'cyan-900'
  | 'cyan-950'
  | 'error-100'
  | 'error-200'
  | 'error-25'
  | 'error-300'
  | 'error-400'
  | 'error-50'
  | 'error-500'
  | 'error-600'
  | 'error-700'
  | 'error-800'
  | 'error-900'
  | 'error-950'
  | 'fuchsia-100'
  | 'fuchsia-200'
  | 'fuchsia-25'
  | 'fuchsia-300'
  | 'fuchsia-400'
  | 'fuchsia-50'
  | 'fuchsia-500'
  | 'fuchsia-600'
  | 'fuchsia-700'
  | 'fuchsia-800'
  | 'fuchsia-900'
  | 'fuchsia-950'
  | 'gray-100'
  | 'gray-200'
  | 'gray-25'
  | 'gray-300'
  | 'gray-400'
  | 'gray-50'
  | 'gray-500'
  | 'gray-600'
  | 'gray-700'
  | 'gray-800'
  | 'gray-900'
  | 'gray-950'
  | 'gray-blue-neutral-100'
  | 'gray-blue-neutral-200'
  | 'gray-blue-neutral-25'
  | 'gray-blue-neutral-300'
  | 'gray-blue-neutral-400'
  | 'gray-blue-neutral-50'
  | 'gray-blue-neutral-500'
  | 'gray-blue-neutral-600'
  | 'gray-blue-neutral-700'
  | 'gray-blue-neutral-800'
  | 'gray-blue-neutral-900'
  | 'gray-blue-neutral-950'
  | 'gray-dark-mode-alpha-100'
  | 'gray-dark-mode-alpha-200'
  | 'gray-dark-mode-alpha-25'
  | 'gray-dark-mode-alpha-300'
  | 'gray-dark-mode-alpha-400'
  | 'gray-dark-mode-alpha-50'
  | 'gray-dark-mode-alpha-500'
  | 'gray-dark-mode-alpha-600'
  | 'gray-dark-mode-alpha-700'
  | 'gray-dark-mode-alpha-800'
  | 'gray-dark-mode-alpha-900'
  | 'gray-dark-mode-alpha-950'
  | 'green-100'
  | 'green-200'
  | 'green-25'
  | 'green-300'
  | 'green-400'
  | 'green-50'
  | 'green-500'
  | 'green-600'
  | 'green-700'
  | 'green-800'
  | 'green-900'
  | 'green-950'
  | 'green-light-100'
  | 'green-light-200'
  | 'green-light-25'
  | 'green-light-300'
  | 'green-light-400'
  | 'green-light-50'
  | 'green-light-500'
  | 'green-light-600'
  | 'green-light-700'
  | 'green-light-800'
  | 'green-light-900'
  | 'green-light-950'
  | 'moss-100'
  | 'moss-200'
  | 'moss-25'
  | 'moss-300'
  | 'moss-400'
  | 'moss-50'
  | 'moss-500'
  | 'moss-600'
  | 'moss-700'
  | 'moss-800'
  | 'moss-900'
  | 'moss-950'
  | 'neutral-100'
  | 'neutral-200'
  | 'neutral-25'
  | 'neutral-300'
  | 'neutral-400'
  | 'neutral-50'
  | 'neutral-500'
  | 'neutral-600'
  | 'neutral-700'
  | 'neutral-800'
  | 'neutral-900'
  | 'neutral-950'
  | 'orange-100'
  | 'orange-200'
  | 'orange-25'
  | 'orange-300'
  | 'orange-400'
  | 'orange-50'
  | 'orange-500'
  | 'orange-600'
  | 'orange-700'
  | 'orange-800'
  | 'orange-900'
  | 'orange-950'
  | 'orange-dark-100'
  | 'orange-dark-200'
  | 'orange-dark-25'
  | 'orange-dark-300'
  | 'orange-dark-400'
  | 'orange-dark-50'
  | 'orange-dark-500'
  | 'orange-dark-600'
  | 'orange-dark-700'
  | 'orange-dark-800'
  | 'orange-dark-900'
  | 'orange-dark-950'
  | 'pink-100'
  | 'pink-200'
  | 'pink-25'
  | 'pink-300'
  | 'pink-400'
  | 'pink-50'
  | 'pink-500'
  | 'pink-600'
  | 'pink-700'
  | 'pink-800'
  | 'pink-900'
  | 'pink-950'
  | 'purple-100'
  | 'purple-200'
  | 'purple-25'
  | 'purple-300'
  | 'purple-400'
  | 'purple-50'
  | 'purple-500'
  | 'purple-600'
  | 'purple-700'
  | 'purple-800'
  | 'purple-900'
  | 'purple-950'
  | 'purple-light-100'
  | 'purple-light-200'
  | 'purple-light-25'
  | 'purple-light-300'
  | 'purple-light-400'
  | 'purple-light-50'
  | 'purple-light-500'
  | 'purple-light-600'
  | 'purple-light-700'
  | 'purple-light-800'
  | 'purple-light-900'
  | 'purple-light-950'
  | 'ros-100'
  | 'ros-200'
  | 'ros-25'
  | 'ros-300'
  | 'ros-400'
  | 'ros-50'
  | 'ros-500'
  | 'ros-600'
  | 'ros-700'
  | 'ros-800'
  | 'ros-900'
  | 'ros-950'
  | 'success-100'
  | 'success-200'
  | 'success-25'
  | 'success-300'
  | 'success-400'
  | 'success-50'
  | 'success-500'
  | 'success-600'
  | 'success-700'
  | 'success-800'
  | 'success-900'
  | 'success-950'
  | 'teal-100'
  | 'teal-200'
  | 'teal-25'
  | 'teal-300'
  | 'teal-400'
  | 'teal-50'
  | 'teal-500'
  | 'teal-600'
  | 'teal-700'
  | 'teal-800'
  | 'teal-900'
  | 'teal-950'
  | 'violet-100'
  | 'violet-200'
  | 'violet-25'
  | 'violet-300'
  | 'violet-400'
  | 'violet-50'
  | 'violet-500'
  | 'violet-600'
  | 'violet-700'
  | 'violet-800'
  | 'violet-900'
  | 'violet-950'
  | 'warning-100'
  | 'warning-200'
  | 'warning-25'
  | 'warning-300'
  | 'warning-400'
  | 'warning-50'
  | 'warning-500'
  | 'warning-600'
  | 'warning-700'
  | 'warning-800'
  | 'warning-900'
  | 'warning-950'
  | 'yellow-100'
  | 'yellow-200'
  | 'yellow-25'
  | 'yellow-300'
  | 'yellow-400'
  | 'yellow-50'
  | 'yellow-500'
  | 'yellow-600'
  | 'yellow-700'
  | 'yellow-800'
  | 'yellow-900'
  | 'yellow-950';

export type SpacingToken =
  | '00-px'
  | '052-px'
  | '10-xl'
  | '1040-px'
  | '11-xl'
  | '120480-px'
  | '1248-px'
  | '14-px'
  | '140560-px'
  | '156-px'
  | '160640-px'
  | '1664-px'
  | '180720-px'
  | '192768-px'
  | '2-xl'
  | '2080-px'
  | '2496-px'
  | '2561024-px'
  | '28-px'
  | '3-xl'
  | '312-px'
  | '3201280-px'
  | '32128-px'
  | '3601440-px'
  | '4-xl'
  | '4001600-px'
  | '40160-px'
  | '416-px'
  | '4801920-px'
  | '48192-px'
  | '5-xl'
  | '520-px'
  | '56224-px'
  | '6-xl'
  | '624-px'
  | '64256-px'
  | '7-xl'
  | '8-xl'
  | '80320-px'
  | '832-px'
  | '9-xl'
  | '96384-px'
  | 'lg'
  | 'md'
  | 'none'
  | 'sm'
  | 'xl'
  | 'xs'
  | 'xxs';

export type RadiusToken =
  | '2-xl'
  | '3-xl'
  | '4-xl'
  | 'full'
  | 'lg'
  | 'md'
  | 'none'
  | 'sm'
  | 'xl'
  | 'xs'
  | 'xxs';

export type FontSizeToken =
  | 'display-2-xl'
  | 'display-lg'
  | 'display-md'
  | 'display-sm'
  | 'display-xl'
  | 'display-xs'
  | 'text-lg'
  | 'text-md'
  | 'text-sm'
  | 'text-xl'
  | 'text-xs';

export type LineHeightToken =
  | 'display-2-xl'
  | 'display-lg'
  | 'display-md'
  | 'display-sm'
  | 'display-xl'
  | 'display-xs'
  | 'text-lg'
  | 'text-md'
  | 'text-sm'
  | 'text-xl'
  | 'text-xs';

export type WidthToken =
  | '2-xl'
  | '3-xl'
  | '4-xl'
  | '5-xl'
  | '6-xl'
  | 'lg'
  | 'md'
  | 'paragraph-max-width'
  | 'sm'
  | 'xl'
  | 'xs'
  | 'xxs';

export type ContainerToken =
  | 'container-max-width-desktop'
  | 'container-padding-desktop'
  | 'container-padding-mobile';

export type TextColorToken =
  | 'brand-primary'
  | 'brand-secondary'
  | 'brand-secondary-hover'
  | 'brand-tertiary'
  | 'brand-tertiary-alt'
  | 'disabled'
  | 'error-primary'
  | 'error-primary-hover'
  | 'placeholder'
  | 'placeholder-subtle'
  | 'primary'
  | 'primary-button'
  | 'quaternary'
  | 'quaternary-on-brand'
  | 'secondary'
  | 'secondary-hover'
  | 'secondary-on-brand'
  | 'success-primary'
  | 'tertiary'
  | 'tertiary-hover'
  | 'tertiary-on-brand'
  | 'warning-primary';

export type BgColorToken =
  | 'active'
  | 'brand-secondary'
  | 'brand-solid'
  | 'brand-solid-hover'
  | 'button-brand-primary'
  | 'disabled'
  | 'disabled-subtle'
  | 'error-primary'
  | 'error-secondary'
  | 'error-solid'
  | 'error-solid-hover'
  | 'overlay'
  | 'primary'
  | 'primary-hover'
  | 'quaternary'
  | 'secondary'
  | 'secondary-hover'
  | 'secondary-solid'
  | 'secondary-subtle'
  | 'success-primary'
  | 'success-secondary'
  | 'success-solid'
  | 'tertiary'
  | 'warning-primary'
  | 'warning-secondary'
  | 'warning-solid';

export type BorderColorToken =
  | 'brand'
  | 'brand-alt'
  | 'disabled'
  | 'disabled-subtle'
  | 'error'
  | 'error-subtle'
  | 'primary'
  | 'secondary'
  | 'secondary-alt'
  | 'tertiary';

export type FgColorToken =
  | 'brand-primary-600'
  | 'brand-primary-alt'
  | 'brand-secondary-500'
  | 'brand-secondary-alt'
  | 'brand-secondary-hover'
  | 'disabled'
  | 'disabled-subtle'
  | 'error-primary'
  | 'error-secondary'
  | 'primary-900'
  | 'quaternary-400'
  | 'quaternary-hover'
  | 'secondary-700'
  | 'secondary-hover'
  | 'success-primary'
  | 'success-secondary'
  | 'tertiary-600'
  | 'tertiary-hover'
  | 'warning-primary'
  | 'warning-secondary'
  | 'white';

export type EffectToken =
  | 'focus-ring'
  | 'focus-ring-error'
  | 'mockup-shadow-grid-md'
  | 'mockup-shadow-main-centre-lg'
  | 'mockup-shadow-main-centre-md'
  | 'mockup-shadow-overlay-lg'
  | 'shadow-2-xl-01'
  | 'shadow-2-xl-02'
  | 'shadow-3-xl-01'
  | 'shadow-3-xl-02'
  | 'shadow-lg-01'
  | 'shadow-lg-02'
  | 'shadow-lg-03'
  | 'shadow-md-01'
  | 'shadow-md-02'
  | 'shadow-skeumorphic-inner'
  | 'shadow-skeumorphic-inner-border'
  | 'shadow-sm-01'
  | 'shadow-sm-02'
  | 'shadow-xl-01'
  | 'shadow-xl-02'
  | 'shadow-xl-03'
  | 'shadow-xs';

export type UtilityColorToken =
  | 'blue-100'
  | 'blue-200'
  | 'blue-300'
  | 'blue-400'
  | 'blue-50'
  | 'blue-500'
  | 'blue-600'
  | 'blue-700'
  | 'blue-dark-100'
  | 'blue-dark-200'
  | 'blue-dark-300'
  | 'blue-dark-400'
  | 'blue-dark-50'
  | 'blue-dark-500'
  | 'blue-dark-600'
  | 'blue-dark-700'
  | 'blue-light-100'
  | 'blue-light-200'
  | 'blue-light-300'
  | 'blue-light-400'
  | 'blue-light-50'
  | 'blue-light-500'
  | 'blue-light-600'
  | 'blue-light-700'
  | 'brand-100'
  | 'brand-100-alt'
  | 'brand-200'
  | 'brand-200-alt'
  | 'brand-300'
  | 'brand-300-alt'
  | 'brand-400'
  | 'brand-400-alt'
  | 'brand-50'
  | 'brand-50-alt'
  | 'brand-500'
  | 'brand-500-alt'
  | 'brand-600'
  | 'brand-600-alt'
  | 'brand-700'
  | 'brand-700-alt'
  | 'brand-800'
  | 'brand-800-alt'
  | 'brand-900'
  | 'brand-900-alt'
  | 'error-100'
  | 'error-200'
  | 'error-300'
  | 'error-400'
  | 'error-50'
  | 'error-500'
  | 'error-600'
  | 'error-700'
  | 'fuchsia-100'
  | 'fuchsia-200'
  | 'fuchsia-300'
  | 'fuchsia-400'
  | 'fuchsia-50'
  | 'fuchsia-500'
  | 'fuchsia-600'
  | 'fuchsia-700'
  | 'gray-100'
  | 'gray-200'
  | 'gray-300'
  | 'gray-400'
  | 'gray-50'
  | 'gray-500'
  | 'gray-600'
  | 'gray-700'
  | 'gray-800'
  | 'gray-900'
  | 'gray-blue-100'
  | 'gray-blue-200'
  | 'gray-blue-300'
  | 'gray-blue-400'
  | 'gray-blue-50'
  | 'gray-blue-500'
  | 'gray-blue-600'
  | 'gray-blue-700'
  | 'green-100'
  | 'green-200'
  | 'green-300'
  | 'green-400'
  | 'green-50'
  | 'green-500'
  | 'green-600'
  | 'green-700'
  | 'indigo-100'
  | 'indigo-200'
  | 'indigo-300'
  | 'indigo-400'
  | 'indigo-50'
  | 'indigo-500'
  | 'indigo-600'
  | 'indigo-700'
  | 'orange-100'
  | 'orange-200'
  | 'orange-300'
  | 'orange-400'
  | 'orange-50'
  | 'orange-500'
  | 'orange-600'
  | 'orange-700'
  | 'orange-dark-100'
  | 'orange-dark-200'
  | 'orange-dark-300'
  | 'orange-dark-400'
  | 'orange-dark-50'
  | 'orange-dark-500'
  | 'orange-dark-600'
  | 'orange-dark-700'
  | 'pink-100'
  | 'pink-200'
  | 'pink-300'
  | 'pink-400'
  | 'pink-50'
  | 'pink-500'
  | 'pink-600'
  | 'pink-700'
  | 'purple-100'
  | 'purple-200'
  | 'purple-300'
  | 'purple-400'
  | 'purple-50'
  | 'purple-500'
  | 'purple-600'
  | 'purple-700'
  | 'success-100'
  | 'success-200'
  | 'success-300'
  | 'success-400'
  | 'success-50'
  | 'success-500'
  | 'success-600'
  | 'success-700'
  | 'warning-100'
  | 'warning-200'
  | 'warning-300'
  | 'warning-400'
  | 'warning-50'
  | 'warning-500'
  | 'warning-600'
  | 'warning-700'
  | 'yellow-100'
  | 'yellow-200'
  | 'yellow-300'
  | 'yellow-400'
  | 'yellow-50'
  | 'yellow-500'
  | 'yellow-600'
  | 'yellow-700';

export type AlphaToken =
  | 'black-10'
  | 'black-100'
  | 'black-20'
  | 'black-30'
  | 'black-40'
  | 'black-50'
  | 'black-60'
  | 'black-70'
  | 'black-80'
  | 'black-90'
  | 'white-10'
  | 'white-100'
  | 'white-20'
  | 'white-30'
  | 'white-40'
  | 'white-50'
  | 'white-60'
  | 'white-70'
  | 'white-80'
  | 'white-90';

export type ComponentToken =
  | 'app-store-badges-app-store-badge-border'
  | 'avatars-avatar-styles-bg-neutral'
  | 'buttons-button-destructive-primary-icon'
  | 'buttons-button-destructive-primary-icon-hover'
  | 'buttons-button-primary-icon'
  | 'buttons-button-primary-icon-hover'
  | 'footers-footer-button-fg'
  | 'footers-footer-button-fg-hover'
  | 'icons-featured-icon-light-fg-brand'
  | 'icons-featured-icon-light-fg-error'
  | 'icons-featured-icon-light-fg-gray'
  | 'icons-featured-icon-light-fg-success'
  | 'icons-featured-icon-light-fg-warning'
  | 'icons-icon-fg-brand'
  | 'icons-icon-fg-brand-on-brand'
  | 'mockups-screen-mockup-border'
  | 'sliders-slider-handle-bg'
  | 'sliders-slider-handle-border'
  | 'text-editor-icon-fg'
  | 'text-editor-icon-fg-active'
  | 'toggles-toggle-border'
  | 'toggles-toggle-button-fg-disabled'
  | 'toggles-toggle-slim-border-pressed'
  | 'toggles-toggle-slim-border-pressed-hover'
  | 'tooltips-tooltip-supporting-text';

/** All semantic token names */
export type SemanticToken =
  | `text-${TextColorToken}`
  | `bg-${BgColorToken}`
  | `border-${BorderColorToken}`
  | `fg-${FgColorToken}`
  | `effect-${EffectToken}`
  | `utility-${UtilityColorToken}`
  | `alpha-${AlphaToken}`
  | `comp-${ComponentToken}`;

/** Theme variants */
export type Theme = 'light' | 'dark';

export interface DesignTokens {
  primitives: Record<PrimitiveColorToken, string>;
  spacing: Record<SpacingToken, string>;
  radius: Record<RadiusToken, string>;
  fontSize: Record<FontSizeToken, string>;
  lineHeight: Record<LineHeightToken, string>;
  width: Record<WidthToken, string>;
  container: Record<ContainerToken, string>;
  text: Record<TextColorToken, string>;
  bg: Record<BgColorToken, string>;
  border: Record<BorderColorToken, string>;
  fg: Record<FgColorToken, string>;
  effect: Record<EffectToken, string>;
  utility: Record<UtilityColorToken, string>;
  alpha: Record<AlphaToken, string>;
  comp: Record<ComponentToken, string>;
  light: Record<SemanticToken, string>;
  dark: Record<SemanticToken, string>;
}

/** Design tokens constant for autocompletion and type safety */
export const tokens = {
  primitives: {
    'base-black': 'var(--primitive-base-black)',
    'base-transparent': 'var(--primitive-base-transparent)',
    'base-white': 'var(--primitive-base-white)',
    'blue-100': 'var(--primitive-blue-100)',
    'blue-200': 'var(--primitive-blue-200)',
    'blue-25': 'var(--primitive-blue-25)',
    'blue-300': 'var(--primitive-blue-300)',
    'blue-400': 'var(--primitive-blue-400)',
    'blue-50': 'var(--primitive-blue-50)',
    'blue-500': 'var(--primitive-blue-500)',
    'blue-600': 'var(--primitive-blue-600)',
    'blue-700': 'var(--primitive-blue-700)',
    'blue-800': 'var(--primitive-blue-800)',
    'blue-900': 'var(--primitive-blue-900)',
    'blue-950': 'var(--primitive-blue-950)',
    'blue-dark-100': 'var(--primitive-blue-dark-100)',
    'blue-dark-200': 'var(--primitive-blue-dark-200)',
    'blue-dark-25': 'var(--primitive-blue-dark-25)',
    'blue-dark-300': 'var(--primitive-blue-dark-300)',
    'blue-dark-400': 'var(--primitive-blue-dark-400)',
    'blue-dark-50': 'var(--primitive-blue-dark-50)',
    'blue-dark-500': 'var(--primitive-blue-dark-500)',
    'blue-dark-600': 'var(--primitive-blue-dark-600)',
    'blue-dark-700': 'var(--primitive-blue-dark-700)',
    'blue-dark-800': 'var(--primitive-blue-dark-800)',
    'blue-dark-900': 'var(--primitive-blue-dark-900)',
    'blue-dark-950': 'var(--primitive-blue-dark-950)',
    'blue-light-100': 'var(--primitive-blue-light-100)',
    'blue-light-200': 'var(--primitive-blue-light-200)',
    'blue-light-25': 'var(--primitive-blue-light-25)',
    'blue-light-300': 'var(--primitive-blue-light-300)',
    'blue-light-400': 'var(--primitive-blue-light-400)',
    'blue-light-50': 'var(--primitive-blue-light-50)',
    'blue-light-500': 'var(--primitive-blue-light-500)',
    'blue-light-600': 'var(--primitive-blue-light-600)',
    'blue-light-700': 'var(--primitive-blue-light-700)',
    'blue-light-800': 'var(--primitive-blue-light-800)',
    'blue-light-900': 'var(--primitive-blue-light-900)',
    'blue-light-950': 'var(--primitive-blue-light-950)',
    'brand-100': 'var(--primitive-brand-100)',
    'brand-200': 'var(--primitive-brand-200)',
    'brand-25': 'var(--primitive-brand-25)',
    'brand-300': 'var(--primitive-brand-300)',
    'brand-400': 'var(--primitive-brand-400)',
    'brand-50': 'var(--primitive-brand-50)',
    'brand-500': 'var(--primitive-brand-500)',
    'brand-600': 'var(--primitive-brand-600)',
    'brand-700': 'var(--primitive-brand-700)',
    'brand-800': 'var(--primitive-brand-800)',
    'brand-900': 'var(--primitive-brand-900)',
    'brand-950': 'var(--primitive-brand-950)',
    'cyan-100': 'var(--primitive-cyan-100)',
    'cyan-200': 'var(--primitive-cyan-200)',
    'cyan-25': 'var(--primitive-cyan-25)',
    'cyan-300': 'var(--primitive-cyan-300)',
    'cyan-400': 'var(--primitive-cyan-400)',
    'cyan-50': 'var(--primitive-cyan-50)',
    'cyan-500': 'var(--primitive-cyan-500)',
    'cyan-600': 'var(--primitive-cyan-600)',
    'cyan-700': 'var(--primitive-cyan-700)',
    'cyan-800': 'var(--primitive-cyan-800)',
    'cyan-900': 'var(--primitive-cyan-900)',
    'cyan-950': 'var(--primitive-cyan-950)',
    'error-100': 'var(--primitive-error-100)',
    'error-200': 'var(--primitive-error-200)',
    'error-25': 'var(--primitive-error-25)',
    'error-300': 'var(--primitive-error-300)',
    'error-400': 'var(--primitive-error-400)',
    'error-50': 'var(--primitive-error-50)',
    'error-500': 'var(--primitive-error-500)',
    'error-600': 'var(--primitive-error-600)',
    'error-700': 'var(--primitive-error-700)',
    'error-800': 'var(--primitive-error-800)',
    'error-900': 'var(--primitive-error-900)',
    'error-950': 'var(--primitive-error-950)',
    'fuchsia-100': 'var(--primitive-fuchsia-100)',
    'fuchsia-200': 'var(--primitive-fuchsia-200)',
    'fuchsia-25': 'var(--primitive-fuchsia-25)',
    'fuchsia-300': 'var(--primitive-fuchsia-300)',
    'fuchsia-400': 'var(--primitive-fuchsia-400)',
    'fuchsia-50': 'var(--primitive-fuchsia-50)',
    'fuchsia-500': 'var(--primitive-fuchsia-500)',
    'fuchsia-600': 'var(--primitive-fuchsia-600)',
    'fuchsia-700': 'var(--primitive-fuchsia-700)',
    'fuchsia-800': 'var(--primitive-fuchsia-800)',
    'fuchsia-900': 'var(--primitive-fuchsia-900)',
    'fuchsia-950': 'var(--primitive-fuchsia-950)',
    'gray-100': 'var(--primitive-gray-100)',
    'gray-200': 'var(--primitive-gray-200)',
    'gray-25': 'var(--primitive-gray-25)',
    'gray-300': 'var(--primitive-gray-300)',
    'gray-400': 'var(--primitive-gray-400)',
    'gray-50': 'var(--primitive-gray-50)',
    'gray-500': 'var(--primitive-gray-500)',
    'gray-600': 'var(--primitive-gray-600)',
    'gray-700': 'var(--primitive-gray-700)',
    'gray-800': 'var(--primitive-gray-800)',
    'gray-900': 'var(--primitive-gray-900)',
    'gray-950': 'var(--primitive-gray-950)',
    'gray-blue-neutral-100': 'var(--primitive-gray-blue-neutral-100)',
    'gray-blue-neutral-200': 'var(--primitive-gray-blue-neutral-200)',
    'gray-blue-neutral-25': 'var(--primitive-gray-blue-neutral-25)',
    'gray-blue-neutral-300': 'var(--primitive-gray-blue-neutral-300)',
    'gray-blue-neutral-400': 'var(--primitive-gray-blue-neutral-400)',
    'gray-blue-neutral-50': 'var(--primitive-gray-blue-neutral-50)',
    'gray-blue-neutral-500': 'var(--primitive-gray-blue-neutral-500)',
    'gray-blue-neutral-600': 'var(--primitive-gray-blue-neutral-600)',
    'gray-blue-neutral-700': 'var(--primitive-gray-blue-neutral-700)',
    'gray-blue-neutral-800': 'var(--primitive-gray-blue-neutral-800)',
    'gray-blue-neutral-900': 'var(--primitive-gray-blue-neutral-900)',
    'gray-blue-neutral-950': 'var(--primitive-gray-blue-neutral-950)',
    'gray-dark-mode-alpha-100': 'var(--primitive-gray-dark-mode-alpha-100)',
    'gray-dark-mode-alpha-200': 'var(--primitive-gray-dark-mode-alpha-200)',
    'gray-dark-mode-alpha-25': 'var(--primitive-gray-dark-mode-alpha-25)',
    'gray-dark-mode-alpha-300': 'var(--primitive-gray-dark-mode-alpha-300)',
    'gray-dark-mode-alpha-400': 'var(--primitive-gray-dark-mode-alpha-400)',
    'gray-dark-mode-alpha-50': 'var(--primitive-gray-dark-mode-alpha-50)',
    'gray-dark-mode-alpha-500': 'var(--primitive-gray-dark-mode-alpha-500)',
    'gray-dark-mode-alpha-600': 'var(--primitive-gray-dark-mode-alpha-600)',
    'gray-dark-mode-alpha-700': 'var(--primitive-gray-dark-mode-alpha-700)',
    'gray-dark-mode-alpha-800': 'var(--primitive-gray-dark-mode-alpha-800)',
    'gray-dark-mode-alpha-900': 'var(--primitive-gray-dark-mode-alpha-900)',
    'gray-dark-mode-alpha-950': 'var(--primitive-gray-dark-mode-alpha-950)',
    'green-100': 'var(--primitive-green-100)',
    'green-200': 'var(--primitive-green-200)',
    'green-25': 'var(--primitive-green-25)',
    'green-300': 'var(--primitive-green-300)',
    'green-400': 'var(--primitive-green-400)',
    'green-50': 'var(--primitive-green-50)',
    'green-500': 'var(--primitive-green-500)',
    'green-600': 'var(--primitive-green-600)',
    'green-700': 'var(--primitive-green-700)',
    'green-800': 'var(--primitive-green-800)',
    'green-900': 'var(--primitive-green-900)',
    'green-950': 'var(--primitive-green-950)',
    'green-light-100': 'var(--primitive-green-light-100)',
    'green-light-200': 'var(--primitive-green-light-200)',
    'green-light-25': 'var(--primitive-green-light-25)',
    'green-light-300': 'var(--primitive-green-light-300)',
    'green-light-400': 'var(--primitive-green-light-400)',
    'green-light-50': 'var(--primitive-green-light-50)',
    'green-light-500': 'var(--primitive-green-light-500)',
    'green-light-600': 'var(--primitive-green-light-600)',
    'green-light-700': 'var(--primitive-green-light-700)',
    'green-light-800': 'var(--primitive-green-light-800)',
    'green-light-900': 'var(--primitive-green-light-900)',
    'green-light-950': 'var(--primitive-green-light-950)',
    'moss-100': 'var(--primitive-moss-100)',
    'moss-200': 'var(--primitive-moss-200)',
    'moss-25': 'var(--primitive-moss-25)',
    'moss-300': 'var(--primitive-moss-300)',
    'moss-400': 'var(--primitive-moss-400)',
    'moss-50': 'var(--primitive-moss-50)',
    'moss-500': 'var(--primitive-moss-500)',
    'moss-600': 'var(--primitive-moss-600)',
    'moss-700': 'var(--primitive-moss-700)',
    'moss-800': 'var(--primitive-moss-800)',
    'moss-900': 'var(--primitive-moss-900)',
    'moss-950': 'var(--primitive-moss-950)',
    'neutral-100': 'var(--primitive-neutral-100)',
    'neutral-200': 'var(--primitive-neutral-200)',
    'neutral-25': 'var(--primitive-neutral-25)',
    'neutral-300': 'var(--primitive-neutral-300)',
    'neutral-400': 'var(--primitive-neutral-400)',
    'neutral-50': 'var(--primitive-neutral-50)',
    'neutral-500': 'var(--primitive-neutral-500)',
    'neutral-600': 'var(--primitive-neutral-600)',
    'neutral-700': 'var(--primitive-neutral-700)',
    'neutral-800': 'var(--primitive-neutral-800)',
    'neutral-900': 'var(--primitive-neutral-900)',
    'neutral-950': 'var(--primitive-neutral-950)',
    'orange-100': 'var(--primitive-orange-100)',
    'orange-200': 'var(--primitive-orange-200)',
    'orange-25': 'var(--primitive-orange-25)',
    'orange-300': 'var(--primitive-orange-300)',
    'orange-400': 'var(--primitive-orange-400)',
    'orange-50': 'var(--primitive-orange-50)',
    'orange-500': 'var(--primitive-orange-500)',
    'orange-600': 'var(--primitive-orange-600)',
    'orange-700': 'var(--primitive-orange-700)',
    'orange-800': 'var(--primitive-orange-800)',
    'orange-900': 'var(--primitive-orange-900)',
    'orange-950': 'var(--primitive-orange-950)',
    'orange-dark-100': 'var(--primitive-orange-dark-100)',
    'orange-dark-200': 'var(--primitive-orange-dark-200)',
    'orange-dark-25': 'var(--primitive-orange-dark-25)',
    'orange-dark-300': 'var(--primitive-orange-dark-300)',
    'orange-dark-400': 'var(--primitive-orange-dark-400)',
    'orange-dark-50': 'var(--primitive-orange-dark-50)',
    'orange-dark-500': 'var(--primitive-orange-dark-500)',
    'orange-dark-600': 'var(--primitive-orange-dark-600)',
    'orange-dark-700': 'var(--primitive-orange-dark-700)',
    'orange-dark-800': 'var(--primitive-orange-dark-800)',
    'orange-dark-900': 'var(--primitive-orange-dark-900)',
    'orange-dark-950': 'var(--primitive-orange-dark-950)',
    'pink-100': 'var(--primitive-pink-100)',
    'pink-200': 'var(--primitive-pink-200)',
    'pink-25': 'var(--primitive-pink-25)',
    'pink-300': 'var(--primitive-pink-300)',
    'pink-400': 'var(--primitive-pink-400)',
    'pink-50': 'var(--primitive-pink-50)',
    'pink-500': 'var(--primitive-pink-500)',
    'pink-600': 'var(--primitive-pink-600)',
    'pink-700': 'var(--primitive-pink-700)',
    'pink-800': 'var(--primitive-pink-800)',
    'pink-900': 'var(--primitive-pink-900)',
    'pink-950': 'var(--primitive-pink-950)',
    'purple-100': 'var(--primitive-purple-100)',
    'purple-200': 'var(--primitive-purple-200)',
    'purple-25': 'var(--primitive-purple-25)',
    'purple-300': 'var(--primitive-purple-300)',
    'purple-400': 'var(--primitive-purple-400)',
    'purple-50': 'var(--primitive-purple-50)',
    'purple-500': 'var(--primitive-purple-500)',
    'purple-600': 'var(--primitive-purple-600)',
    'purple-700': 'var(--primitive-purple-700)',
    'purple-800': 'var(--primitive-purple-800)',
    'purple-900': 'var(--primitive-purple-900)',
    'purple-950': 'var(--primitive-purple-950)',
    'purple-light-100': 'var(--primitive-purple-light-100)',
    'purple-light-200': 'var(--primitive-purple-light-200)',
    'purple-light-25': 'var(--primitive-purple-light-25)',
    'purple-light-300': 'var(--primitive-purple-light-300)',
    'purple-light-400': 'var(--primitive-purple-light-400)',
    'purple-light-50': 'var(--primitive-purple-light-50)',
    'purple-light-500': 'var(--primitive-purple-light-500)',
    'purple-light-600': 'var(--primitive-purple-light-600)',
    'purple-light-700': 'var(--primitive-purple-light-700)',
    'purple-light-800': 'var(--primitive-purple-light-800)',
    'purple-light-900': 'var(--primitive-purple-light-900)',
    'purple-light-950': 'var(--primitive-purple-light-950)',
    'ros-100': 'var(--primitive-ros-100)',
    'ros-200': 'var(--primitive-ros-200)',
    'ros-25': 'var(--primitive-ros-25)',
    'ros-300': 'var(--primitive-ros-300)',
    'ros-400': 'var(--primitive-ros-400)',
    'ros-50': 'var(--primitive-ros-50)',
    'ros-500': 'var(--primitive-ros-500)',
    'ros-600': 'var(--primitive-ros-600)',
    'ros-700': 'var(--primitive-ros-700)',
    'ros-800': 'var(--primitive-ros-800)',
    'ros-900': 'var(--primitive-ros-900)',
    'ros-950': 'var(--primitive-ros-950)',
    'success-100': 'var(--primitive-success-100)',
    'success-200': 'var(--primitive-success-200)',
    'success-25': 'var(--primitive-success-25)',
    'success-300': 'var(--primitive-success-300)',
    'success-400': 'var(--primitive-success-400)',
    'success-50': 'var(--primitive-success-50)',
    'success-500': 'var(--primitive-success-500)',
    'success-600': 'var(--primitive-success-600)',
    'success-700': 'var(--primitive-success-700)',
    'success-800': 'var(--primitive-success-800)',
    'success-900': 'var(--primitive-success-900)',
    'success-950': 'var(--primitive-success-950)',
    'teal-100': 'var(--primitive-teal-100)',
    'teal-200': 'var(--primitive-teal-200)',
    'teal-25': 'var(--primitive-teal-25)',
    'teal-300': 'var(--primitive-teal-300)',
    'teal-400': 'var(--primitive-teal-400)',
    'teal-50': 'var(--primitive-teal-50)',
    'teal-500': 'var(--primitive-teal-500)',
    'teal-600': 'var(--primitive-teal-600)',
    'teal-700': 'var(--primitive-teal-700)',
    'teal-800': 'var(--primitive-teal-800)',
    'teal-900': 'var(--primitive-teal-900)',
    'teal-950': 'var(--primitive-teal-950)',
    'violet-100': 'var(--primitive-violet-100)',
    'violet-200': 'var(--primitive-violet-200)',
    'violet-25': 'var(--primitive-violet-25)',
    'violet-300': 'var(--primitive-violet-300)',
    'violet-400': 'var(--primitive-violet-400)',
    'violet-50': 'var(--primitive-violet-50)',
    'violet-500': 'var(--primitive-violet-500)',
    'violet-600': 'var(--primitive-violet-600)',
    'violet-700': 'var(--primitive-violet-700)',
    'violet-800': 'var(--primitive-violet-800)',
    'violet-900': 'var(--primitive-violet-900)',
    'violet-950': 'var(--primitive-violet-950)',
    'warning-100': 'var(--primitive-warning-100)',
    'warning-200': 'var(--primitive-warning-200)',
    'warning-25': 'var(--primitive-warning-25)',
    'warning-300': 'var(--primitive-warning-300)',
    'warning-400': 'var(--primitive-warning-400)',
    'warning-50': 'var(--primitive-warning-50)',
    'warning-500': 'var(--primitive-warning-500)',
    'warning-600': 'var(--primitive-warning-600)',
    'warning-700': 'var(--primitive-warning-700)',
    'warning-800': 'var(--primitive-warning-800)',
    'warning-900': 'var(--primitive-warning-900)',
    'warning-950': 'var(--primitive-warning-950)',
    'yellow-100': 'var(--primitive-yellow-100)',
    'yellow-200': 'var(--primitive-yellow-200)',
    'yellow-25': 'var(--primitive-yellow-25)',
    'yellow-300': 'var(--primitive-yellow-300)',
    'yellow-400': 'var(--primitive-yellow-400)',
    'yellow-50': 'var(--primitive-yellow-50)',
    'yellow-500': 'var(--primitive-yellow-500)',
    'yellow-600': 'var(--primitive-yellow-600)',
    'yellow-700': 'var(--primitive-yellow-700)',
    'yellow-800': 'var(--primitive-yellow-800)',
    'yellow-900': 'var(--primitive-yellow-900)',
    'yellow-950': 'var(--primitive-yellow-950)',
  },  spacing: {
    '00-px': 'var(--spacing-00-px)',
    '052-px': 'var(--spacing-052-px)',
    '10-xl': 'var(--spacing-10-xl)',
    '1040-px': 'var(--spacing-1040-px)',
    '11-xl': 'var(--spacing-11-xl)',
    '120480-px': 'var(--spacing-120480-px)',
    '1248-px': 'var(--spacing-1248-px)',
    '14-px': 'var(--spacing-14-px)',
    '140560-px': 'var(--spacing-140560-px)',
    '156-px': 'var(--spacing-156-px)',
    '160640-px': 'var(--spacing-160640-px)',
    '1664-px': 'var(--spacing-1664-px)',
    '180720-px': 'var(--spacing-180720-px)',
    '192768-px': 'var(--spacing-192768-px)',
    '2-xl': 'var(--spacing-2-xl)',
    '2080-px': 'var(--spacing-2080-px)',
    '2496-px': 'var(--spacing-2496-px)',
    '2561024-px': 'var(--spacing-2561024-px)',
    '28-px': 'var(--spacing-28-px)',
    '3-xl': 'var(--spacing-3-xl)',
    '312-px': 'var(--spacing-312-px)',
    '3201280-px': 'var(--spacing-3201280-px)',
    '32128-px': 'var(--spacing-32128-px)',
    '3601440-px': 'var(--spacing-3601440-px)',
    '4-xl': 'var(--spacing-4-xl)',
    '4001600-px': 'var(--spacing-4001600-px)',
    '40160-px': 'var(--spacing-40160-px)',
    '416-px': 'var(--spacing-416-px)',
    '4801920-px': 'var(--spacing-4801920-px)',
    '48192-px': 'var(--spacing-48192-px)',
    '5-xl': 'var(--spacing-5-xl)',
    '520-px': 'var(--spacing-520-px)',
    '56224-px': 'var(--spacing-56224-px)',
    '6-xl': 'var(--spacing-6-xl)',
    '624-px': 'var(--spacing-624-px)',
    '64256-px': 'var(--spacing-64256-px)',
    '7-xl': 'var(--spacing-7-xl)',
    '8-xl': 'var(--spacing-8-xl)',
    '80320-px': 'var(--spacing-80320-px)',
    '832-px': 'var(--spacing-832-px)',
    '9-xl': 'var(--spacing-9-xl)',
    '96384-px': 'var(--spacing-96384-px)',
    'lg': 'var(--spacing-lg)',
    'md': 'var(--spacing-md)',
    'none': 'var(--spacing-none)',
    'sm': 'var(--spacing-sm)',
    'xl': 'var(--spacing-xl)',
    'xs': 'var(--spacing-xs)',
    'xxs': 'var(--spacing-xxs)',
  },  radius: {
    '2-xl': 'var(--radius-2-xl)',
    '3-xl': 'var(--radius-3-xl)',
    '4-xl': 'var(--radius-4-xl)',
    'full': 'var(--radius-full)',
    'lg': 'var(--radius-lg)',
    'md': 'var(--radius-md)',
    'none': 'var(--radius-none)',
    'sm': 'var(--radius-sm)',
    'xl': 'var(--radius-xl)',
    'xs': 'var(--radius-xs)',
    'xxs': 'var(--radius-xxs)',
  },  fontSize: {
    'display-2-xl': 'var(--font-size-display-2-xl)',
    'display-lg': 'var(--font-size-display-lg)',
    'display-md': 'var(--font-size-display-md)',
    'display-sm': 'var(--font-size-display-sm)',
    'display-xl': 'var(--font-size-display-xl)',
    'display-xs': 'var(--font-size-display-xs)',
    'text-lg': 'var(--font-size-text-lg)',
    'text-md': 'var(--font-size-text-md)',
    'text-sm': 'var(--font-size-text-sm)',
    'text-xl': 'var(--font-size-text-xl)',
    'text-xs': 'var(--font-size-text-xs)',
  },  lineHeight: {
    'display-2-xl': 'var(--line-height-display-2-xl)',
    'display-lg': 'var(--line-height-display-lg)',
    'display-md': 'var(--line-height-display-md)',
    'display-sm': 'var(--line-height-display-sm)',
    'display-xl': 'var(--line-height-display-xl)',
    'display-xs': 'var(--line-height-display-xs)',
    'text-lg': 'var(--line-height-text-lg)',
    'text-md': 'var(--line-height-text-md)',
    'text-sm': 'var(--line-height-text-sm)',
    'text-xl': 'var(--line-height-text-xl)',
    'text-xs': 'var(--line-height-text-xs)',
  },  width: {
    '2-xl': 'var(--width-2-xl)',
    '3-xl': 'var(--width-3-xl)',
    '4-xl': 'var(--width-4-xl)',
    '5-xl': 'var(--width-5-xl)',
    '6-xl': 'var(--width-6-xl)',
    'lg': 'var(--width-lg)',
    'md': 'var(--width-md)',
    'paragraph-max-width': 'var(--width-paragraph-max-width)',
    'sm': 'var(--width-sm)',
    'xl': 'var(--width-xl)',
    'xs': 'var(--width-xs)',
    'xxs': 'var(--width-xxs)',
  },  container: {
    'container-max-width-desktop': 'var(--container-container-max-width-desktop)',
    'container-padding-desktop': 'var(--container-container-padding-desktop)',
    'container-padding-mobile': 'var(--container-container-padding-mobile)',
  },  text: {
    'brand-primary': 'var(--text-brand-primary)',
    'brand-secondary': 'var(--text-brand-secondary)',
    'brand-secondary-hover': 'var(--text-brand-secondary-hover)',
    'brand-tertiary': 'var(--text-brand-tertiary)',
    'brand-tertiary-alt': 'var(--text-brand-tertiary-alt)',
    'disabled': 'var(--text-disabled)',
    'error-primary': 'var(--text-error-primary)',
    'error-primary-hover': 'var(--text-error-primary-hover)',
    'placeholder': 'var(--text-placeholder)',
    'placeholder-subtle': 'var(--text-placeholder-subtle)',
    'primary': 'var(--text-primary)',
    'primary-button': 'var(--text-primary-button)',
    'quaternary': 'var(--text-quaternary)',
    'quaternary-on-brand': 'var(--text-quaternary-on-brand)',
    'secondary': 'var(--text-secondary)',
    'secondary-hover': 'var(--text-secondary-hover)',
    'secondary-on-brand': 'var(--text-secondary-on-brand)',
    'success-primary': 'var(--text-success-primary)',
    'tertiary': 'var(--text-tertiary)',
    'tertiary-hover': 'var(--text-tertiary-hover)',
    'tertiary-on-brand': 'var(--text-tertiary-on-brand)',
    'warning-primary': 'var(--text-warning-primary)',
  },  bg: {
    'active': 'var(--bg-active)',
    'brand-secondary': 'var(--bg-brand-secondary)',
    'brand-solid': 'var(--bg-brand-solid)',
    'brand-solid-hover': 'var(--bg-brand-solid-hover)',
    'button-brand-primary': 'var(--bg-button-brand-primary)',
    'disabled': 'var(--bg-disabled)',
    'disabled-subtle': 'var(--bg-disabled-subtle)',
    'error-primary': 'var(--bg-error-primary)',
    'error-secondary': 'var(--bg-error-secondary)',
    'error-solid': 'var(--bg-error-solid)',
    'error-solid-hover': 'var(--bg-error-solid-hover)',
    'overlay': 'var(--bg-overlay)',
    'primary': 'var(--bg-primary)',
    'primary-hover': 'var(--bg-primary-hover)',
    'quaternary': 'var(--bg-quaternary)',
    'secondary': 'var(--bg-secondary)',
    'secondary-hover': 'var(--bg-secondary-hover)',
    'secondary-solid': 'var(--bg-secondary-solid)',
    'secondary-subtle': 'var(--bg-secondary-subtle)',
    'success-primary': 'var(--bg-success-primary)',
    'success-secondary': 'var(--bg-success-secondary)',
    'success-solid': 'var(--bg-success-solid)',
    'tertiary': 'var(--bg-tertiary)',
    'warning-primary': 'var(--bg-warning-primary)',
    'warning-secondary': 'var(--bg-warning-secondary)',
    'warning-solid': 'var(--bg-warning-solid)',
  },  border: {
    'brand': 'var(--border-brand)',
    'brand-alt': 'var(--border-brand-alt)',
    'disabled': 'var(--border-disabled)',
    'disabled-subtle': 'var(--border-disabled-subtle)',
    'error': 'var(--border-error)',
    'error-subtle': 'var(--border-error-subtle)',
    'primary': 'var(--border-primary)',
    'secondary': 'var(--border-secondary)',
    'secondary-alt': 'var(--border-secondary-alt)',
    'tertiary': 'var(--border-tertiary)',
  },  fg: {
    'brand-primary-600': 'var(--fg-brand-primary-600)',
    'brand-primary-alt': 'var(--fg-brand-primary-alt)',
    'brand-secondary-500': 'var(--fg-brand-secondary-500)',
    'brand-secondary-alt': 'var(--fg-brand-secondary-alt)',
    'brand-secondary-hover': 'var(--fg-brand-secondary-hover)',
    'disabled': 'var(--fg-disabled)',
    'disabled-subtle': 'var(--fg-disabled-subtle)',
    'error-primary': 'var(--fg-error-primary)',
    'error-secondary': 'var(--fg-error-secondary)',
    'primary-900': 'var(--fg-primary-900)',
    'quaternary-400': 'var(--fg-quaternary-400)',
    'quaternary-hover': 'var(--fg-quaternary-hover)',
    'secondary-700': 'var(--fg-secondary-700)',
    'secondary-hover': 'var(--fg-secondary-hover)',
    'success-primary': 'var(--fg-success-primary)',
    'success-secondary': 'var(--fg-success-secondary)',
    'tertiary-600': 'var(--fg-tertiary-600)',
    'tertiary-hover': 'var(--fg-tertiary-hover)',
    'warning-primary': 'var(--fg-warning-primary)',
    'warning-secondary': 'var(--fg-warning-secondary)',
    'white': 'var(--fg-white)',
  },  effect: {
    'focus-ring': 'var(--effect-focus-ring)',
    'focus-ring-error': 'var(--effect-focus-ring-error)',
    'mockup-shadow-grid-md': 'var(--effect-mockup-shadow-grid-md)',
    'mockup-shadow-main-centre-lg': 'var(--effect-mockup-shadow-main-centre-lg)',
    'mockup-shadow-main-centre-md': 'var(--effect-mockup-shadow-main-centre-md)',
    'mockup-shadow-overlay-lg': 'var(--effect-mockup-shadow-overlay-lg)',
    'shadow-2-xl-01': 'var(--effect-shadow-2-xl-01)',
    'shadow-2-xl-02': 'var(--effect-shadow-2-xl-02)',
    'shadow-3-xl-01': 'var(--effect-shadow-3-xl-01)',
    'shadow-3-xl-02': 'var(--effect-shadow-3-xl-02)',
    'shadow-lg-01': 'var(--effect-shadow-lg-01)',
    'shadow-lg-02': 'var(--effect-shadow-lg-02)',
    'shadow-lg-03': 'var(--effect-shadow-lg-03)',
    'shadow-md-01': 'var(--effect-shadow-md-01)',
    'shadow-md-02': 'var(--effect-shadow-md-02)',
    'shadow-skeumorphic-inner': 'var(--effect-shadow-skeumorphic-inner)',
    'shadow-skeumorphic-inner-border': 'var(--effect-shadow-skeumorphic-inner-border)',
    'shadow-sm-01': 'var(--effect-shadow-sm-01)',
    'shadow-sm-02': 'var(--effect-shadow-sm-02)',
    'shadow-xl-01': 'var(--effect-shadow-xl-01)',
    'shadow-xl-02': 'var(--effect-shadow-xl-02)',
    'shadow-xl-03': 'var(--effect-shadow-xl-03)',
    'shadow-xs': 'var(--effect-shadow-xs)',
  },  utility: {
    'blue-100': 'var(--utility-blue-100)',
    'blue-200': 'var(--utility-blue-200)',
    'blue-300': 'var(--utility-blue-300)',
    'blue-400': 'var(--utility-blue-400)',
    'blue-50': 'var(--utility-blue-50)',
    'blue-500': 'var(--utility-blue-500)',
    'blue-600': 'var(--utility-blue-600)',
    'blue-700': 'var(--utility-blue-700)',
    'blue-dark-100': 'var(--utility-blue-dark-100)',
    'blue-dark-200': 'var(--utility-blue-dark-200)',
    'blue-dark-300': 'var(--utility-blue-dark-300)',
    'blue-dark-400': 'var(--utility-blue-dark-400)',
    'blue-dark-50': 'var(--utility-blue-dark-50)',
    'blue-dark-500': 'var(--utility-blue-dark-500)',
    'blue-dark-600': 'var(--utility-blue-dark-600)',
    'blue-dark-700': 'var(--utility-blue-dark-700)',
    'blue-light-100': 'var(--utility-blue-light-100)',
    'blue-light-200': 'var(--utility-blue-light-200)',
    'blue-light-300': 'var(--utility-blue-light-300)',
    'blue-light-400': 'var(--utility-blue-light-400)',
    'blue-light-50': 'var(--utility-blue-light-50)',
    'blue-light-500': 'var(--utility-blue-light-500)',
    'blue-light-600': 'var(--utility-blue-light-600)',
    'blue-light-700': 'var(--utility-blue-light-700)',
    'brand-100': 'var(--utility-brand-100)',
    'brand-100-alt': 'var(--utility-brand-100-alt)',
    'brand-200': 'var(--utility-brand-200)',
    'brand-200-alt': 'var(--utility-brand-200-alt)',
    'brand-300': 'var(--utility-brand-300)',
    'brand-300-alt': 'var(--utility-brand-300-alt)',
    'brand-400': 'var(--utility-brand-400)',
    'brand-400-alt': 'var(--utility-brand-400-alt)',
    'brand-50': 'var(--utility-brand-50)',
    'brand-50-alt': 'var(--utility-brand-50-alt)',
    'brand-500': 'var(--utility-brand-500)',
    'brand-500-alt': 'var(--utility-brand-500-alt)',
    'brand-600': 'var(--utility-brand-600)',
    'brand-600-alt': 'var(--utility-brand-600-alt)',
    'brand-700': 'var(--utility-brand-700)',
    'brand-700-alt': 'var(--utility-brand-700-alt)',
    'brand-800': 'var(--utility-brand-800)',
    'brand-800-alt': 'var(--utility-brand-800-alt)',
    'brand-900': 'var(--utility-brand-900)',
    'brand-900-alt': 'var(--utility-brand-900-alt)',
    'error-100': 'var(--utility-error-100)',
    'error-200': 'var(--utility-error-200)',
    'error-300': 'var(--utility-error-300)',
    'error-400': 'var(--utility-error-400)',
    'error-50': 'var(--utility-error-50)',
    'error-500': 'var(--utility-error-500)',
    'error-600': 'var(--utility-error-600)',
    'error-700': 'var(--utility-error-700)',
    'fuchsia-100': 'var(--utility-fuchsia-100)',
    'fuchsia-200': 'var(--utility-fuchsia-200)',
    'fuchsia-300': 'var(--utility-fuchsia-300)',
    'fuchsia-400': 'var(--utility-fuchsia-400)',
    'fuchsia-50': 'var(--utility-fuchsia-50)',
    'fuchsia-500': 'var(--utility-fuchsia-500)',
    'fuchsia-600': 'var(--utility-fuchsia-600)',
    'fuchsia-700': 'var(--utility-fuchsia-700)',
    'gray-100': 'var(--utility-gray-100)',
    'gray-200': 'var(--utility-gray-200)',
    'gray-300': 'var(--utility-gray-300)',
    'gray-400': 'var(--utility-gray-400)',
    'gray-50': 'var(--utility-gray-50)',
    'gray-500': 'var(--utility-gray-500)',
    'gray-600': 'var(--utility-gray-600)',
    'gray-700': 'var(--utility-gray-700)',
    'gray-800': 'var(--utility-gray-800)',
    'gray-900': 'var(--utility-gray-900)',
    'gray-blue-100': 'var(--utility-gray-blue-100)',
    'gray-blue-200': 'var(--utility-gray-blue-200)',
    'gray-blue-300': 'var(--utility-gray-blue-300)',
    'gray-blue-400': 'var(--utility-gray-blue-400)',
    'gray-blue-50': 'var(--utility-gray-blue-50)',
    'gray-blue-500': 'var(--utility-gray-blue-500)',
    'gray-blue-600': 'var(--utility-gray-blue-600)',
    'gray-blue-700': 'var(--utility-gray-blue-700)',
    'green-100': 'var(--utility-green-100)',
    'green-200': 'var(--utility-green-200)',
    'green-300': 'var(--utility-green-300)',
    'green-400': 'var(--utility-green-400)',
    'green-50': 'var(--utility-green-50)',
    'green-500': 'var(--utility-green-500)',
    'green-600': 'var(--utility-green-600)',
    'green-700': 'var(--utility-green-700)',
    'indigo-100': 'var(--utility-indigo-100)',
    'indigo-200': 'var(--utility-indigo-200)',
    'indigo-300': 'var(--utility-indigo-300)',
    'indigo-400': 'var(--utility-indigo-400)',
    'indigo-50': 'var(--utility-indigo-50)',
    'indigo-500': 'var(--utility-indigo-500)',
    'indigo-600': 'var(--utility-indigo-600)',
    'indigo-700': 'var(--utility-indigo-700)',
    'orange-100': 'var(--utility-orange-100)',
    'orange-200': 'var(--utility-orange-200)',
    'orange-300': 'var(--utility-orange-300)',
    'orange-400': 'var(--utility-orange-400)',
    'orange-50': 'var(--utility-orange-50)',
    'orange-500': 'var(--utility-orange-500)',
    'orange-600': 'var(--utility-orange-600)',
    'orange-700': 'var(--utility-orange-700)',
    'orange-dark-100': 'var(--utility-orange-dark-100)',
    'orange-dark-200': 'var(--utility-orange-dark-200)',
    'orange-dark-300': 'var(--utility-orange-dark-300)',
    'orange-dark-400': 'var(--utility-orange-dark-400)',
    'orange-dark-50': 'var(--utility-orange-dark-50)',
    'orange-dark-500': 'var(--utility-orange-dark-500)',
    'orange-dark-600': 'var(--utility-orange-dark-600)',
    'orange-dark-700': 'var(--utility-orange-dark-700)',
    'pink-100': 'var(--utility-pink-100)',
    'pink-200': 'var(--utility-pink-200)',
    'pink-300': 'var(--utility-pink-300)',
    'pink-400': 'var(--utility-pink-400)',
    'pink-50': 'var(--utility-pink-50)',
    'pink-500': 'var(--utility-pink-500)',
    'pink-600': 'var(--utility-pink-600)',
    'pink-700': 'var(--utility-pink-700)',
    'purple-100': 'var(--utility-purple-100)',
    'purple-200': 'var(--utility-purple-200)',
    'purple-300': 'var(--utility-purple-300)',
    'purple-400': 'var(--utility-purple-400)',
    'purple-50': 'var(--utility-purple-50)',
    'purple-500': 'var(--utility-purple-500)',
    'purple-600': 'var(--utility-purple-600)',
    'purple-700': 'var(--utility-purple-700)',
    'success-100': 'var(--utility-success-100)',
    'success-200': 'var(--utility-success-200)',
    'success-300': 'var(--utility-success-300)',
    'success-400': 'var(--utility-success-400)',
    'success-50': 'var(--utility-success-50)',
    'success-500': 'var(--utility-success-500)',
    'success-600': 'var(--utility-success-600)',
    'success-700': 'var(--utility-success-700)',
    'warning-100': 'var(--utility-warning-100)',
    'warning-200': 'var(--utility-warning-200)',
    'warning-300': 'var(--utility-warning-300)',
    'warning-400': 'var(--utility-warning-400)',
    'warning-50': 'var(--utility-warning-50)',
    'warning-500': 'var(--utility-warning-500)',
    'warning-600': 'var(--utility-warning-600)',
    'warning-700': 'var(--utility-warning-700)',
    'yellow-100': 'var(--utility-yellow-100)',
    'yellow-200': 'var(--utility-yellow-200)',
    'yellow-300': 'var(--utility-yellow-300)',
    'yellow-400': 'var(--utility-yellow-400)',
    'yellow-50': 'var(--utility-yellow-50)',
    'yellow-500': 'var(--utility-yellow-500)',
    'yellow-600': 'var(--utility-yellow-600)',
    'yellow-700': 'var(--utility-yellow-700)',
  },
  alpha: {
    'black-10': 'var(--alpha-black-10)',
    'black-100': 'var(--alpha-black-100)',
    'black-20': 'var(--alpha-black-20)',
    'black-30': 'var(--alpha-black-30)',
    'black-40': 'var(--alpha-black-40)',
    'black-50': 'var(--alpha-black-50)',
    'black-60': 'var(--alpha-black-60)',
    'black-70': 'var(--alpha-black-70)',
    'black-80': 'var(--alpha-black-80)',
    'black-90': 'var(--alpha-black-90)',
    'white-10': 'var(--alpha-white-10)',
    'white-100': 'var(--alpha-white-100)',
    'white-20': 'var(--alpha-white-20)',
    'white-30': 'var(--alpha-white-30)',
    'white-40': 'var(--alpha-white-40)',
    'white-50': 'var(--alpha-white-50)',
    'white-60': 'var(--alpha-white-60)',
    'white-70': 'var(--alpha-white-70)',
    'white-80': 'var(--alpha-white-80)',
    'white-90': 'var(--alpha-white-90)',
  },
  comp: {
    'app-store-badges-app-store-badge-border': 'var(--comp-app-store-badges-app-store-badge-border)',
    'avatars-avatar-styles-bg-neutral': 'var(--comp-avatars-avatar-styles-bg-neutral)',
    'buttons-button-destructive-primary-icon': 'var(--comp-buttons-button-destructive-primary-icon)',
    'buttons-button-destructive-primary-icon-hover': 'var(--comp-buttons-button-destructive-primary-icon-hover)',
    'buttons-button-primary-icon': 'var(--comp-buttons-button-primary-icon)',
    'buttons-button-primary-icon-hover': 'var(--comp-buttons-button-primary-icon-hover)',
    'footers-footer-button-fg': 'var(--comp-footers-footer-button-fg)',
    'footers-footer-button-fg-hover': 'var(--comp-footers-footer-button-fg-hover)',
    'icons-featured-icon-light-fg-brand': 'var(--comp-icons-featured-icon-light-fg-brand)',
    'icons-featured-icon-light-fg-error': 'var(--comp-icons-featured-icon-light-fg-error)',
    'icons-featured-icon-light-fg-gray': 'var(--comp-icons-featured-icon-light-fg-gray)',
    'icons-featured-icon-light-fg-success': 'var(--comp-icons-featured-icon-light-fg-success)',
    'icons-featured-icon-light-fg-warning': 'var(--comp-icons-featured-icon-light-fg-warning)',
    'icons-icon-fg-brand': 'var(--comp-icons-icon-fg-brand)',
    'icons-icon-fg-brand-on-brand': 'var(--comp-icons-icon-fg-brand-on-brand)',
    'mockups-screen-mockup-border': 'var(--comp-mockups-screen-mockup-border)',
    'sliders-slider-handle-bg': 'var(--comp-sliders-slider-handle-bg)',
    'sliders-slider-handle-border': 'var(--comp-sliders-slider-handle-border)',
    'text-editor-icon-fg': 'var(--comp-text-editor-icon-fg)',
    'text-editor-icon-fg-active': 'var(--comp-text-editor-icon-fg-active)',
    'toggles-toggle-border': 'var(--comp-toggles-toggle-border)',
    'toggles-toggle-button-fg-disabled': 'var(--comp-toggles-toggle-button-fg-disabled)',
    'toggles-toggle-slim-border-pressed': 'var(--comp-toggles-toggle-slim-border-pressed)',
    'toggles-toggle-slim-border-pressed-hover': 'var(--comp-toggles-toggle-slim-border-pressed-hover)',
    'tooltips-tooltip-supporting-text': 'var(--comp-tooltips-tooltip-supporting-text)',
  },
} as const;

